### ISSUE TITLE
Runtime error in iOS: "SWIFT TASK CONTINUATION MISUSE: persistentModelID() leaked its continuation!"

### ISSUE THREAD

**Issue by BrianBatchelder** [Whiffer/swiftdata-transferrable#1]
I'm trying to use your package for an iOS app. I made a couple of mods to your sample app to get it to build and run on iOS. 
- Add NavigationStack around views in ContentView, so toolbar is visible.
- Remove dropProposal section of ItemsListView, as iOS doesn't support NSEvent.

Once I did that, the app runs. But whenever I drag a view on top of Target1View or Target2View, the warning "SWIFT TASK CONTINUATION MISUSE: persistentModelID() leaked its continuation!" is spit-out to the log. In addition, there is an icon indicating that the dragging view cannot be dropped on the target view.

Thoughts? Thanks.

EDIT: The failure seems to be that the `completionHandler` is never called after the call to `self.loadTransferable()` in `NSItemProvider.swift`.

**Comment by Whiffer** [comment]
Hi Brian,
I have not tried to use this with iOS yet, but I do intend to do so.  I am unable at the moment, but will try when I can.  It would help if you could attach a copy of my sample program with the modifications you made to get it to run on iOS.
Thanks.
Chuck

**Comment by BrianBatchelder** [comment]
Here's the patch to get iOS "working": [patch.patch](https://github.com/Whiffer/swiftdata-transferrable/files/14288619/patch.patch)

**Comment by Whiffer** [comment]
Here's what I can see so far.  The package does seem to work as expected on macOS, but on  iOS, the continuation is leaked because the completion handler for the call to loadTransferable is never called, therefore the continuation is never resumed. This is probably also the reason that the drop targets do not get targeted.   Either I'm missing something or this is a bug in loadTransferable on iOS.  I'll dig deeper and keep you posted. Thanks.

**Comment by Whiffer** [comment]
As you may have already noticed, I just posted a Version 2.0 of this package.  It does not use a DropDelegate, which totally avoids the need to use loadTransferrable, and therefore the leaked continuation.  This package now seems to work well with both iOS and macOS, however, in doing so, I had to remove support for my new dropProposal parameter of the dropDestination view modifier.  I'll add it back if I can figure out another way to accomplish that on all platforms.  Thanks.

**Comment by BrianBatchelder** [comment]
I'll give it a try. Thanks!

**Comment by BrianBatchelder** [comment]
I finally found some time to test your fix. It's working fine. I'll let you know if I discover any other problems.

**Comment by Whiffer** [comment]
Thanks for letting me know.
